### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by robinwhittleton** [dajare/mary-seacole_wonderful-adventures-of-mrs-seacole-in-many-lands#1]
general
- KBC is one of the (incredibly named) Orders of the Bath. So it should have a `z3998:name-title` semantic instead of `z3998:initialism`. See https://standardebooks.org/manual/1.7.3/single-page#8.10.5 . Same for H.S.H., Hon., C.B., etc.

content.opf
- Add a fullname entry of “Mary Jane Seacole”
- W.S.J. has a role of `edt` which sounds reasonable. Below them though is an `ann` role which is assigned to `author`, i.e. a duplicate of Mary’s role. Let’s change that to `#editor`, and change the role to `src` which is what comes up when searching https://www.loc.gov/marc/relators/relaterm.html for amanuensis.

dedication
- I think I’d be bumping the `line-height` in the CSS rather than using successive `<br>`s. But maybe that’s just me?

halftitlepage
- Missing an `<abbr>` for Mrs.

chapter-8
- Seeing as there’s a load of `datetime`s elsewhere in the book, we can add `1855-01-25` to “the 25th of January”

colophon
- Missing an `<abbr>` for Mrs.

**Comment by dajare** [comment]
Thanks for these, @robinwhittleton - some comments (where required, otherwise, "done!"):

- `name-title` : I checked all `initialism` instances; only three remain. The rest are now `name-title`.

**content.opf**
- two things for "W. S. J.":
    1. the `ann` role is because both Seacole and WSJ seem to have contributed [an endnote each][e]: WSJ the first, and Seacole the second; so I've left that `ann` for now (but fixed the incorrect `refines=`, no doubt my copy/paste error);
    2. I take it you mean `scr` for "Scribe" rather than `src` as written? Should I still add this one for WSJ (I haven't as yet).
- Also, the "full-name" for Russell wrongly refined `author`, so I've fixed that.

**dedication.xhtml** - I think that was just left-over PG markup, and I forgot about it! I've removed the extra `br`'s and added 2.5em line-height, which looks about right to my eye. Hope that works.

And missing semantics added.

I hope that's caught everything! If you could let me know about WSJ (whether to drop his `ann` and/or add a `scr`), that would be great. Thanks!

[e]: https://github.com/dajare/mary-seacole_wonderful-adventures-of-mrs-seacole-in-many-lands/blob/master/src/epub/text/endnotes.xhtml

**Comment by robinwhittleton** [comment]
Yep, `scr` (I write too much HTML for a living 😅)

**Comment by dajare** [comment]
Ha! :wink:  Okay - that's done now. I *added* the `scr` role. If I misunderstood about the other roles for WJS, please do tell. Otherwise, if you're content, it's ready for Alex. Thanks again!
